language: python
python:
  - "3.6"

# command to install dependencies
install:

  - pip install -r requirements.txt

services:
  - postgresql

after_success:
  coveralls
# command to run tests
script: 
  - nosetests tests/
  - nosetests  --with-coverage --cover-package=app