sudo: true
language: python
python:
  - "3.6"

# command to install dependencies
install:

  - pip install -r requirements.txt

services:
  - postgresql

# env:
#   global:
#     - SECRET = os.getenv('SECRET')
#     - SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL')
#     - SQLALCHEMY_DATABASE_URI = 'postgresql://localhost/test_db'

before_script:
  # - createdb test_test_db
  # - python manage.py db init
  # - python manage.py db migrate
  # - python manage.py db upgrade
  - psql -c "CREATE DATABASE test_db;" -U postgres
after_success:
  coveralls
# command to run tests
script: 
  - nosetests  --with-coverage --cover-package=app