sudo: true
language: python
python:
  - "3.6"

# command to install dependencies
install:

  - pip install -r requirements.txt

services:
  - postgresql

env:
  global:
    - export SECRET="THISis@secret54321"
    - export APP_SETTINGS="testing"
    - export DATABASE_URL="postgresql://localhost/test_db"

before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
after_success:
  coveralls
# command to run tests
script: 
  - nosetests  --with-coverage --cover-package=app